We essentially only require jax and optax for the main features.

In [ ]:
import optax as otx
import jax
import jax.numpy as jnp

We divide the main code into two modules, `yaqsi` and `operations`.
In the future this might be merged for convenience.

In [ ]:
import qml_essentials.yaqsi as ys
import qml_essentials.operations as op

Building a circuit is very similar to e.g. Pennylane; operations are recorded on a tape, and you pass parameters and wires upon instantiation.
However, there is a slight difference regarding the obervables; those are not directly part of the circuit but specified seperatly instead..

In [11]:
def circuit():
    op.H(wires=0)
    op.CX(wires=[0, 1])

obs = [op.PauliZ(wires=0), op.PauliZ(wires=1)]

And passed to the `execute` method together with the execution `type` (either `probs`, `expval`, `state` or `density`).
Note that the number of qubits is automatically inferred from the operations on the tape.

In [12]:
yss = ys.Script(circuit)
yss.execute(type="probs", obs=obs)

Array([0.5, 0. , 0. , 0.5], dtype=float64)

Now, let's go for sth., more complex.
We utilize caching so you can expect this code to run even faster if you execute it a second time.

In [ ]:
n_qubits = 20

def circuit():
    op.H(wires=0)
    for i in range(n_qubits):
        op.CX(wires=[i, i + 1])

obs = [op.PauliZ(wires=i) for i in range(n_qubits)]
yss = ys.Script(circuit)
yss.execute(type="expval", obs=obs)

Array([0.5, 0. , 0. , ..., 0. , 0. , 0.5], dtype=float64)

Parametrized circuits are also supported, similar to what you would do in Pennylane,
with the only difference that you have to pass the parameters to the `execute` method.

In [ ]:
n_qubits = 1

def circuit(phi, theta, omega):
    op.Rot(phi, theta, omega, wires=0)
    op.Rot(jnp.pi, 1/2*jnp.pi, 1/4*jnp.pi, wires=0)

obs = [op.PauliZ(wires=i) for i in range(n_qubits)]
yss = ys.Script(circuit)
yss.execute(type="expval", obs=obs, args=(jnp.pi, 1/2*jnp.pi, 1/4*jnp.pi))

Array([0.70710678], dtype=float64)

Getting parameterized circuits to train is a breeze by simply adding optax to your code.
Note that this is all standard code, and not specific to `yaqsi`.

In [ ]:
def cost_fct(params):
    phi, theta, omega = params
    return yss.execute(type="expval", obs=[op.PauliZ(0)], args=(phi, theta, omega))[0]

params = jax.numpy.array([0.1, 0.2, 0.3])
opt = otx.adam(0.01)
opt_state = opt.init(params)

for epoch in range(1, 101):
    grads = jax.grad(cost_fct)(params)
    updates, opt_state = opt.update(grads, opt_state, params)
    params = otx.apply_updates(params, updates)

    if epoch % 10 == 0:
        print(f"Epoch: {epoch}, Cost: {cost_fct(params):.4f}")

[0.1 0.2 0.3]
[ 0.1        -0.77972245 -0.01600711]


Now for some more "exotic" features; you can use e.g. random unitaries...

In [ ]:
n_qubits = 10
key = jax.random.PRNGKey(42)

def circuit():
    op.RandomUnitary(wires=list(range(n_qubits)), key=key)

obs = [op.PauliZ(wires=i) for i in range(n_qubits)]
yss = ys.Script(circuit)
yss.execute(type="density", obs=obs).shape

(1024, 1024)

... call `.dagger()` or `.power(...)`...

In [ ]:
def circuit():
        op.RX(0.5, wires=0)
        op.RX(0.5, wires=0).dagger()
        op.PauliX(wires=0).power(2)

obs = [op.PauliZ(0)]
yss = ys.Script(circuit)
res = yss.execute(type="expval", obs=obs)

print(res) # we expect to end up in |0⟩ again

... use different noise channels...

In [ ]:
def circuit():
    op.H(wires=0)
    op.CX(wires=[0, 1])
    op.DepolarizingChannel(0.1, wires=0)
    op.DepolarizingChannel(0.1, wires=1)

obs = [op.PauliZ(0)]
yss = ys.Script(circuit)
rho = yss.execute(type="density", obs=obs)
purity = jnp.real(jnp.trace(rho @ rho))
print(purity) # Purity should be < 1 

... or do pulse level simulation of circuits

In [ ]:
from qml_essentials.gates import PulseGates

def circuit(w):
    PulseGates.RX(w, wires=0)

obs = [op.PauliZ(0)]
yss = ys.Script(circuit)
res = yss.execute(type="expval", obs=obs)